// Product Data
const products = [
  {
    id: 1,
    name: "Oversized Logo Hoodie",
    category: "Hoodies",
    gender: "unisex",
    price: 189,
    salePrice: null,
    tag: "New",
    image: "/black-oversized-hoodie-streetwear.jpg",
    images: ["/black-oversized-hoodie-front.jpg", "/black-oversized-hoodie-back.jpg", "/black-oversized-hoodie-detail.jpg"],
    description:
      "Premium heavyweight cotton hoodie with oversized fit. Features embroidered logo and ribbed cuffs for durability and style.",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 2,
    name: "Cargo Tech Pants",
    category: "Pants",
    gender: "mens",
    price: 145,
    salePrice: null,
    tag: "Bestseller",
    image: "/black-cargo-pants-streetwear.png",
    images: ["/black-cargo-pants-front.jpg", "/black-cargo-pants-pocket-detail.jpg", "/black-cargo-pants-side.jpg"],
    description:
      "Technical cargo pants with multiple utility pockets. Water-resistant fabric with adjustable ankle cuffs.",
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: 3,
    name: "Graphic Print Tee",
    category: "T-Shirts",
    gender: "unisex",
    price: 75,
    salePrice: 49,
    tag: "Sale",
    image: "/black-graphic-tshirt-streetwear.jpg",
    images: ["/black-graphic-tshirt-front.jpg", "/black-graphic-tshirt-back.jpg", "/black-tshirt-detail.png"],
    description: "100% organic cotton tee with exclusive screen-printed graphics. Relaxed fit for everyday comfort.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 4,
    name: "Utility Vest",
    category: "Outerwear",
    gender: "mens",
    price: 225,
    salePrice: null,
    tag: "Limited",
    image: "/black-tactical-vest-utility.jpg",
    images: ["/black-tactical-vest-front.jpg", "/black-tactical-vest-back.jpg", "/black-tactical-vest-detail.jpg"],
    description: "Multi-pocket utility vest with adjustable straps. Perfect layering piece for any streetwear look.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 5,
    name: "Essential Cap",
    category: "Accessories",
    gender: "unisex",
    price: 55,
    salePrice: 35,
    tag: "Sale",
    image: "/black-cap-minimal-embroidered.jpg",
    images: [
      "/black-cap-front.jpg",
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
    ],
    description: "Classic six-panel cap with embroidered logo. Adjustable strap for perfect fit.",
    sizes: ["One Size"],
  },
  {
    id: 6,
    name: "Heavyweight Crewneck",
    category: "Hoodies",
    gender: "unisex",
    price: 135,
    salePrice: null,
    tag: null,
    image: "/placeholder.svg?height=600&width=450",
    images: [
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
    ],
    description: "Heavyweight fleece crewneck with dropped shoulders. Garment-dyed for a vintage look.",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 7,
    name: "Cropped Hoodie",
    category: "Hoodies",
    gender: "womens",
    price: 159,
    salePrice: null,
    tag: "New",
    image: "/placeholder.svg?height=600&width=450",
    images: [
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
    ],
    description: "Cropped silhouette hoodie with raw hem. Perfect for high-waisted bottoms.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 8,
    name: "Wide Leg Joggers",
    category: "Pants",
    gender: "womens",
    price: 125,
    salePrice: 89,
    tag: "Sale",
    image: "/placeholder.svg?height=600&width=450",
    images: [
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
    ],
    description: "Relaxed wide-leg joggers with elastic waist. Premium French terry fabric.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 9,
    name: "Chain Necklace",
    category: "Accessories",
    gender: "unisex",
    price: 95,
    salePrice: null,
    tag: "New",
    image: "/placeholder.svg?height=600&width=450",
    images: [
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
    ],
    description: "Stainless steel chain with custom pendant. Hypoallergenic and tarnish-resistant.",
    sizes: ['18"', '22"'],
  },
  {
    id: 10,
    name: "Biker Shorts",
    category: "Pants",
    gender: "womens",
    price: 65,
    salePrice: 45,
    tag: "Sale",
    image: "/placeholder.svg?height=600&width=450",
    images: [
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
    ],
    description: "High-waisted biker shorts with buttery soft fabric. Perfect for street style or workout.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 11,
    name: "Bomber Jacket",
    category: "Outerwear",
    gender: "mens",
    price: 285,
    salePrice: 199,
    tag: "Sale",
    image: "/placeholder.svg?height=600&width=450",
    images: [
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
    ],
    description: "Classic bomber jacket with satin finish. Ribbed collar, cuffs, and hem.",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 12,
    name: "Bucket Hat",
    category: "Accessories",
    gender: "unisex",
    price: 45,
    salePrice: null,
    tag: null,
    image: "/placeholder.svg?height=600&width=450",
    images: [
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
      "/placeholder.svg?height=600&width=450",
    ],
    description: "Classic bucket hat with embroidered logo. 100% cotton twill construction.",
    sizes: ["S/M", "L/XL"],
  },
]

// Team Data
const team = [
  {
    id: "sarah",
    name: "Sarah Chen",
    role: "Designer",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Sarah brings over 10 years of fashion design experience to NOIR STREET. Her innovative approach to streetwear has shaped our brand's unique aesthetic.",
    email: "sarah@noirstreet.com",
    linkedin: "linkedin.com/in/sarahchen",
    experience: [
      {
        date: "2020 - Present",
        title: "Lead Designer",
        company: "NOIR STREET",
        desc: "Leading the creative direction for all seasonal collections and collaborations.",
      },
      {
        date: "2016 - 2020",
        title: "Senior Designer",
        company: "Urban Collective",
        desc: "Designed menswear and womens streetwear collections for global markets.",
      },
      {
        date: "2013 - 2016",
        title: "Junior Designer",
        company: "MODE Studio",
        desc: "Started career creating technical specs and assisting with runway shows.",
      },
    ],
    skills: [
      "Fashion Design",
      "Pattern Making",
      "Adobe Creative Suite",
      "3D CLO",
      "Trend Forecasting",
      "Sustainable Design",
    ],
  },
  {
    id: "john",
    name: "John Martinez",
    role: "Engineer",
    image: "/placeholder.svg?height=400&width=400",
    bio: "John is the technical backbone of NOIR STREET, building and maintaining our e-commerce platform and supply chain systems.",
    email: "john@noirstreet.com",
    linkedin: "linkedin.com/in/johnmartinez",
    experience: [
      {
        date: "2021 - Present",
        title: "Lead Engineer",
        company: "NOIR STREET",
        desc: "Architecting scalable e-commerce solutions and leading the engineering team.",
      },
      {
        date: "2018 - 2021",
        title: "Full Stack Developer",
        company: "TechFlow Inc",
        desc: "Built custom web applications for retail and fashion industry clients.",
      },
      {
        date: "2015 - 2018",
        title: "Frontend Developer",
        company: "Digital Agency Co",
        desc: "Created responsive websites and interactive experiences for brands.",
      },
    ],
    skills: ["JavaScript", "React", "Node.js", "Python", "AWS", "PostgreSQL", "System Architecture"],
  },
  {
    id: "liam",
    name: "Liam O'Connor",
    role: "Toilet Scrubber",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Liam keeps our headquarters spotless and running smoothly. His attention to detail and positive attitude make him an invaluable team member.",
    email: "liam@noirstreet.com",
    linkedin: "linkedin.com/in/liamoconnor",
    experience: [
      {
        date: "2022 - Present",
        title: "Facilities Specialist",
        company: "NOIR STREET",
        desc: "Maintaining pristine office conditions and ensuring a healthy work environment.",
      },
      {
        date: "2019 - 2022",
        title: "Senior Custodian",
        company: "CleanPro Services",
        desc: "Managed cleaning operations for multiple commercial properties.",
      },
      {
        date: "2016 - 2019",
        title: "Maintenance Associate",
        company: "City Mall Complex",
        desc: "Handled daily cleaning and minor maintenance tasks for retail spaces.",
      },
    ],
    skills: [
      "Sanitation Protocols",
      "Equipment Maintenance",
      "OSHA Compliance",
      "Green Cleaning",
      "Time Management",
      "Problem Solving",
    ],
  },
]

// Categories
const categories = [
  { name: "All", slug: "all" },
  { name: "Hoodies", slug: "hoodies" },
  { name: "T-Shirts", slug: "tshirts" },
  { name: "Pants", slug: "pants" },
  { name: "Outerwear", slug: "outerwear" },
  { name: "Accessories", slug: "accessories" },
]
